[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loro = { path = "../loro" }
fxhash = { workspace = true }
enum_dispatch = { workspace = true }
enum-as-inner = { workspace = true }
rand = "0.8.5"
tracing = "0.1"
arbitrary = "1"
tabled = "0.10"

[dev-dependencies]
ctor = "0.2"
arbtest = "^0.2.0"
dev-utils = { path = "../dev-utils" }
tracing-subscriber = "0.3.18"
color-backtrace = "0.6.1"
